stages:
  - build
  - run

variables:
  IMAGE_NAME: "lsj-ubuntu14-image"

build_image:
  stage: build
  script:
    - echo "Docker 이미지 빌드 시작"
    - docker build -t $IMAGE_NAME .

run_container:
  stage: run
  tags:
    - docker
  script:
    - echo "Docker 컨테이너 실행 시작"
    - docker run -d --name ubuntu14-container $IMAGE_NAME
